export const DANG_NHAP_ACTION = 'DANG_NHAP_ACTION'

export const DANG_KY_ACTION = 'DANG_KY_ACTION'


// export const CAP_NHAT_NGUOI_DUNG = 'CAP_NHAT_NGUOI_DUNG'

export const SET_THONG_TIN_NGUOI_DUNG = 'SET_THONG_TIN_NGUOI_DUNG'


export const LAY_DANH_SACH_NGUOI_DUNG = 'LAY_DANH_SACH_NGUOI_DUNG'

export const SET_THONG_TIN_USER = 'SET_THONG_TIN_USER'



